from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()


class Basic(db.Model):
    company_name = db.Column(db.String(500))
    company_number = db.Column(db.String(50), primary_key=True)
    reg_address_care_of = db.Column(db.String(500))
    reg_address_po_box = db.Column(db.String(500))
    reg_address_address_line1 = db.Column(db.String(500))
    reg_address_address_line2 = db.Column(db.String(500))
    reg_address_post_town = db.Column(db.String(500))
    reg_address_county = db.Column(db.String(500))
    reg_address_country = db.Column(db.String(500))
    reg_address_post_code = db.Column(db.String(500))
    company_category = db.Column(db.String(500))
    company_status = db.Column(db.String(500))
    country_of_origin = db.Column(db.String(500))
    dissolution_date = db.Column(db.String(500))
    incorporation_date = db.Column(db.String(500))
    accounts_account_ref_day = db.Column(db.String(500))
    accounts_account_ref_month = db.Column(db.String(500))
    accounts_next_due_date = db.Column(db.String(500))
    accounts_last_made_up_date = db.Column(db.String(500))
    accounts_account_category = db.Column(db.String(500))
    returns_next_due_date = db.Column(db.String(500))
    returns_last_made_up_date = db.Column(db.String(500))
    mortgages_num_mort_charges = db.Column(db.String(500))
    mortgages_num_mort_outstanding = db.Column(db.String(500))
    mortgages_num_mort_part_satisfied = db.Column(db.String(500))
    mortgages_num_mort_satisfied = db.Column(db.String(500))
    sic_code_sic_text_1 = db.Column(db.String(500))
    sic_code_sic_text_2 = db.Column(db.String(500))
    sic_code_sic_text_3 = db.Column(db.String(500))
    sic_code_sic_text_4 = db.Column(db.String(500))
    limited_partnerships_num_gen_partners = db.Column(db.String(500))
    limited_partnerships_num_lim_partners = db.Column(db.String(500))
    uri = db.Column(db.String(500))
    previous_name_1_condate = db.Column(db.String(500))
    previous_name_1_company_name = db.Column(db.String(500))
    previous_name_2_condate = db.Column(db.String(500))
    previous_name_2_company_name = db.Column(db.String(500))
    previous_name_3_condate = db.Column(db.String(500))
    previous_name_3_company_name = db.Column(db.String(500))
    previous_name_4_condate = db.Column(db.String(500))
    previous_name_4_company_name = db.Column(db.String(500))
    previous_name_5_condate = db.Column(db.String(500))
    previous_name_5_company_name = db.Column(db.String(500))
    previous_name_6_condate = db.Column(db.String(500))
    previous_name_6_company_name = db.Column(db.String(500))
    previous_name_7_condate = db.Column(db.String(500))
    previous_name_7_company_name = db.Column(db.String(500))
    previous_name_8_condate = db.Column(db.String(500))
    previous_name_8_company_name = db.Column(db.String(500))
    previous_name_9_condate = db.Column(db.String(500))
    previous_name_9_company_name = db.Column(db.String(500))
    previous_name_10_condate = db.Column(db.String(500))
    previous_name_10_company_name = db.Column(db.String(500))
    conf_stmt_next_due_date = db.Column(db.String(500))
    conf_stmt_last_made_up_date = db.Column(db.String(500))


def __repr__(self):
    return '<Basic %r>' % self.company_name
